templates/files/config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :sessions, only: [:new, :create, :destroy]
    get 'login', to: 'sessions#new'
    get 'logout', to: 'sessions#destroy'

    root to: 'dashboard#index'
  end

  root to: 'home#index'
end

templates/files/app/models/account.rb
class Account < ActiveRecord::Base
  has_secure_password

  validates :email, presence: true, uniqueness: true
end

templates/files/app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  PER_PAGE = 25

  before_action :authorize

  protect_from_forgery with: :exception
  layout 'admin/application'

  private

  def current_user
    @current_user ||= Account.find(session[:account_id]) if session[:account_id]
  end
  helper_method :current_user

  def authorize
    redirect_to admin_login_url unless current_user
  end
end

templates/files/app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
  def index
  end
end

templates/files/app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ApplicationController
  layout 'admin/login'

  def new
  end

  def create
    account = Account.find_by(email: params[:email])
    if account && account.authenticate(params[:password])
      session[:account_id] = account.id
      redirect_to admin_root_path
    else
      flash[:notice] = 'Invalid email or password'
      render :new
    end
  end

  def destroy
    session[:account_id] = nil
    redirect_to login_path
  end
end

templates/files/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

templates/files/app/views/admin/dashboard/index.slim
h1 Dashboard

templates/files/app/views/home/index.slim
h1 Application Name

templates/files/app/views/layouts/admin/application.slim
doctype html
html class="no-js"
  head
    meta charset="utf-8"
    = csrf_meta_tags

    title Application Name

    = stylesheet_link_tag    "admin", media: "all"
    = javascript_include_tag "admin"

  body class="admin"
    nav class="navbar navbar-default navbar-fixed-top"
      .container
        = link_to 'Administration', admin_root_path, class: 'navbar-brand'

        ul class="nav navbar-nav"
          li
            = link_to 'Dashboard', admin_root_path

        p class="navbar-text navbar-right signed-in"
          | Signed in as:&nbsp;
          strong = current_user.email

          = link_to admin_logout_path, style: 'color: white' do
            i.glyphicon.glyphicon-logo-out
            | Logout

    .container
      - flash.each do |type, msg|
        = content_tag :div, msg, class: "alert alert-info"
      = yield

templates/files/app/views/layouts/admin/login.slim
doctype html
html class="no-js"
  head
    meta charset="utf-8"
    = csrf_meta_tags

    title Application Name

    = stylesheet_link_tag    "admin", media: "all"
    = javascript_include_tag "admin"

  body class="admin login"
    - flash.each do |type, msg|
      = content_tag :div, msg, class: "alert alert-info"

    = yield

templates/files/app/views/layouts/application.slim
doctype html
html class="no-js"
  head
    meta charset="utf-8"
    = csrf_meta_tags

    title Application Name

    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"

  body
    = yield